version: '3.8'

services:
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./database/SQL/:/docker-entrypoint-initdb.d/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - 8080:80
    depends_on:
      - postgresdb

  app:
    depends_on:
      - postgresdb
    build: ./
    ports:
      - 8000:8000
    environment:
      - DB_HOST=postgresdb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydatabase
      - DB_PORT=5432
    stdin_open: true
    tty: true
    volumes:
      - ./src:/usr/src/app/src

volumes:
  db:
